global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/alerts.yml"

scrape_configs:
  - job_name: 'opina'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/monitoring/metrics'
    scheme: 'http' 